name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: android-actions/setup-android@v3

      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - name: List APK files
        run: find . -name "*.apk"

      - name: Run Tests
        run: ./gradlew test --stacktrace
        continue-on-error: true

      - name: Run Lint
        run: ./gradlew lint --stacktrace
        continue-on-error: true

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-artifacts
          path: |
            app/build/outputs/apk/
            app/build/outputs/bundle/
          retention-days: 7

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            app/build/reports/
            app/build/test-results/
          retention-days: 7

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-report
          path: app/build/reports/lint-results*.html
          retention-days: 7        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-artifacts
          path: |
            app/build/outputs/apk/
            app/build/outputs/bundle/
          retention-days: 7

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            app/build/reports/
            app/build/test-results/
          retention-days: 7

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-report
          path: app/build/reports/lint-results*.html
          retention-days: 7    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: build-artifacts
        path: |
          app/build/outputs/apk/
          app/build/outputs/bundle/
        retention-days: 7
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          app/build/reports/
          app/build/test-results/
        retention-days: 7
        
    - name: Upload Lint Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lint-report
        path: app/build/reports/lint-results*.html
        retention-days: 7          
    - name: Build with Gradle
      run: ./gradlew build --stacktrace
      
    - name: Run Tests
      run: ./gradlew test --stacktrace
      continue-on-error: true
      
    - name: Run Lint
      run: ./gradlew lint --stacktrace
      continue-on-error: true
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: build-artifacts
        path: |
          app/build/outputs/apk/
          app/build/outputs/bundle/
        retention-days: 7
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: |
          app/build/reports/
          app/build/test-results/
        retention-days: 7
        
    - name: Upload Lint Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: lint-report
        path: app/build/reports/lint-results*.html
        retention-days: 7          
    - name: Build with Gradle
      run: ./gradlew build --stacktrace
      
    - name: Run Tests
      run: ./gradlew test --stacktrace
      continue-on-error: true
      
    - name: Run Lint
      run: ./gradlew lint --stacktrace
      continue-on-error: true
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: build-artifacts
        path: |
          app/build/outputs/apk/
          app/build/outputs/bundle/
        retention-days: 7
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          app/build/reports/
          app/build/test-results/
        retention-days: 7
        
    - name: Upload Lint Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lint-report
        path: app/build/reports/lint-results*.html
        retention-days: 7          
    - name: Build with Gradle
      run: ./gradlew build --stacktrace
      
    - name: Run Tests
      run: ./gradlew test --stacktrace
      continue-on-error: true
      
    - name: Run Lint
      run: ./gradlew lint --stacktrace
      continue-on-error: true
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: build-artifacts
        path: |
          app/build/outputs/apk/
          app/build/outputs/bundle/
        retention-days: 7
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: |
          app/build/reports/
          app/build/test-results/
        retention-days: 7
        
    - name: Upload Lint Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: lint-report
        path: app/build/reports/lint-results*.html
        retention-days: 7
